In [1]:
# ตัวอย่าง ข้อมูลแบบภาพสี
import cv2
import numpy as np
img = cv2.imread('./image/digits_dataset/0_1.png')
img.shape, img

((20, 20, 3),
 array([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        ...,
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]], dtype=uint8))

In [2]:
# ตัวอย่าง ข้อมูลแบบภาพขาวดำ
import cv2
import numpy as np
img = cv2.imread('./image/digits_dataset/0_1.png')
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
gray.shape, gray

((20, 20),
 array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  28,  24,
           0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,  34, 118, 171, 192,
         106,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0, 113, 142,  63,  30,  86,
         207,  37,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0, 104, 214, 185,   0,   0,   0,
         168, 103,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,  87, 134,  27,  56,   5,   0,   0,
         123, 158,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,  30, 158,  33,   0,   0,   0,   0,   0,
          91, 176,   4,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,  91

In [3]:
train = np.array([]) 
for i in range(6): 
    for j in range(1, 251):
        img   = cv2.imread('./image/digits_dataset/'+str(i)+'_'+str(j)+'.png') 
        gray  = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        train = np.append(train, gray) 
train = train.reshape(-1, 400).astype(np. float32)
print('Get Data for train - Ok')

test = np.array([]) 
for i in range(6): 
    for j in range(251, 501):
        img = cv2.imread('./image/digits_dataset/' +str(i)+'_'+str(j)+'.png') 
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        test = np.append(test, gray) 
test = test.reshape (-1, 400).astype (np. float32)
print('Get Data for test - Ok')


Get Data for train - Ok
Get Data for test - Ok


In [4]:
k = np.arange(6)
train_labels = np.repeat(k, 250)[:,np.newaxis] 
test_labels  = train_labels.copy ()

knn = cv2.ml.KNearest_create() 
knn.train(train, cv2.ml.ROW_SAMPLE, train_labels)
ret, result, neighbours, dist = knn.findNearest(test, k=5) 
result.shape, result


((1500, 1),
 array([[0.],
        [0.],
        [0.],
        ...,
        [5.],
        [5.],
        [5.]], dtype=float32))

In [5]:
import sys
np.set_printoptions(threshold=sys.maxsize)

k = np.arange(6)
train_labels = np.repeat(k, 250)[:,np.newaxis] 
test_labels  = train_labels.copy ()

knn = cv2.ml.KNearest_create() 
knn.train(train, cv2.ml.ROW_SAMPLE, train_labels)
ret, result, neighbours, dist = knn.findNearest(test, k=5) 
result.shape, result


((1500, 1),
 array([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [5.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        

In [6]:
matches  = result == test_labels 
correct  = np.count_nonzero(matches)
accuracy = correct * 100.0 / result.size 
print('accuracy = ', accuracy)


accuracy =  95.86666666666666


In [9]:
#mydigit = cv2.imread('./image/unknown_x.png') 
#mydigit = cv2.imread('./image/unknown_y.png') 
mydigit = cv2.imread('./image/unknown_z.png') 

cv2.imshow('detected digit', mydigit)
mydigit_gray = cv2.cvtColor(mydigit, cv2.COLOR_BGR2GRAY) 
mydigit_test = mydigit_gray.reshape (-1,400).astype(np. float32)
ret, result, neighbours, dist = knn. findNearest (mydigit_test, k=5) 
print(ret)

font = cv2.FONT_HERSHEY_SIMPLEX 
cv2.putText(mydigit, str(int(ret)), (0, 7), font, 0.3, (255, 0, 0), 1, cv2.LINE_AA)

cv2.waitKey (0)
cv2.destroyAllWindows ()


5.0
